/* ===== TERH · lang-en.js — compléments de traduction anglaise =====
 * Format : 'texte français exact' : 'English text'.
 * - Les émojis au début et la ponctuation à la fin sont ignorés par le traducteur.
 * - Après modification : rechargez la page (le fichier est servi en no-cache).
 * - Ajout à chaud depuis la console : TERH_I18N_add({'Bonjour':'Hello'})
 */
window.TERH_I18N=Object.assign(window.TERH_I18N||{},{
"Vue générale": "Overview",
"Rôles & permissions": "Roles & permissions",
"Tableaux de bord": "Dashboards",
"Textes": "Texts",
"Bases de données": "Databases",
"Droit social": "Labour law",
"Alertes gratuites": "Free alerts",
"Profil & web": "Profile & web",
"Papier à en-tête": "Letterhead",
"Bibliothèque": "Library",
"En-tête lettres": "Letter header",
"Modèle Sanction": "Sanction template",
"Modèle DE": "Demobilisation template",
"Documents bibliothèque": "Library documents",
"Erreurs locales": "Local errors",
"Employés": "Employees",
"Congés": "Leave",
"En-tête des lettres de démobilisation": "Demobilisation letter header",
"Image du papier à en-tête": "Letterhead image",
"Choisir l'image": "Choose image",
"Enregistrer l'image": "Save image",
"Retirer": "Remove",
"Enregistrer l'en-tête": "Save header",
"Valeurs par défaut": "Default values",
"Aperçu de l'en-tête": "Header preview",
"Société": "Company",
"Ville (lieu de la lettre)": "City (letter location)",
"Adresse": "Address",
"Téléphone(s)": "Phone number(s)",
"Email": "Email",
"Service / direction": "Department / division",
"Mise à disposition": "Secondment (staff placement)",
"Automatique (si l'entreprise a une société mère)": "Automatic (if the company has a parent company)",
"Toujours afficher la société mère": "Always show the parent company",
"Jamais": "Never",
"Société mère (nom)": "Parent company (name)",
"Adresse de la société mère": "Parent company address",
"Libellé de mise à disposition": "Secondment wording",
"Mentions légales (RCCM, NIU, BP… une ligne par mention)": "Legal notices (trade register, tax ID, P.O. Box… one line each)",
"Mis à disposition auprès de": "Seconded to",
"Bandeau en haut de page (lettres, certificats, DE, sanctions). En mise à disposition, l'image de la société mère est utilisée si l'entreprise n'a pas la sienne.": "Banner at the top of the page (letters, certificates, demobilisation, sanctions). For seconded staff, the parent company image is used if the company has none of its own.",
"Modifiez la société et ses informations affichées en haut des lettres. En cas de mise à disposition, la société mère figure sur le papier à en-tête.": "Edit the company and the details shown at the top of letters. For seconded staff, the parent company appears on the letterhead.",
"Importer un nouveau modèle": "Import a new template",
"Fichier Word (.docx), PDF, .txt, .html, .rtf ou image (OCR). Le contenu est chargé dans le modèle choisi ; vérifiez-le puis enregistrez.": "Word (.docx), PDF, .txt, .html, .rtf or image (OCR) file. The content is loaded into the chosen template; check it, then save.",
"Choisir un fichier": "Choose a file",
"Enregistrer ce modèle": "Save this template",
"Le modèle importé s'affiche ici": "The imported template appears here",
"Lecture de": "Reading",
"Chargé : vérifiez puis enregistrez": "Loaded: check, then save",
"Modèle vide": "Empty template",
"Modèle enregistré": "Template saved",
"Modèle chargé : vérifiez l'aperçu puis enregistrez": "Template loaded: check the preview, then save",
"Fichier trop volumineux (max 5 Mo)": "File too large (max 5 MB)",
"Format non supporté": "Unsupported format",
"Word, PDF, .txt, .html, .rtf ou image, puis": "Word, PDF, .txt, .html, .rtf or image, then",
"En-tête enregistré": "Header saved",
"Permission refusée": "Permission denied",
"Aperçu indisponible": "Preview unavailable",
"Choisissez d'abord une image": "Choose an image first",
"Papier à en-tête enregistré": "Letterhead saved",
"Retiré": "Removed",
"Retirer le papier à en-tête ?": "Remove the letterhead?",
"Aperçu chargé — cliquez sur Enregistrer": "Preview loaded — click Save",
"Livres, conventions collectives, codes, procédures. Les textes sont enregistrés dans IndexedDB : ils restent lisibles par l'IA et l'assistant même sans internet.": "Books, collective agreements, codes, procedures. Texts are stored in IndexedDB: they stay readable by the AI and the assistant even without internet.",
"Ajouter des fichiers (PDF, DOCX, TXT, HTML, RTF)": "Add files (PDF, DOCX, TXT, HTML, RTF)",
"Aucun document.": "No documents.",
"Supprimer ce document ?": "Delete this document?",
"Supprimé": "Deleted",
"car.": "chars",
"Maintenance": "Maintenance",
"Recharger les données": "Reload data",
"Vider le cache local": "Clear local cache",
"Rapport de diagnostic": "Diagnostic report",
"Sauvegarde JSON": "JSON backup",
"Journal d'erreurs local": "Local error log",
"Aucune erreur.": "No errors.",
"Données rechargées": "Data reloaded",
"Cache vidé": "Cache cleared",
"Rapport copié": "Report copied",
"Vider le cache local (les données en ligne restent) ?": "Clear the local cache (online data is kept)?",
"Sauvegarde : utilisez Paramètres › Sauvegarde": "Backup: use Settings › Backup",
"Personnalisation avancée de la plateforme": "Advanced platform customisation",
"Ces réglages s'appliquent à l'entreprise active (et sont mémorisés sur cet appareil).": "These settings apply to the active company (and are saved on this device).",
"Nom affiché dans la barre (vide = automatique : société mère › société cliente)": "Name shown in the top bar (empty = automatic: parent company › client company)",
"Actualisation auto assistant (désactivée : utilisez le bouton 🔄)": "Assistant auto-refresh (disabled: use the 🔄 button)",
"Taille du texte (px)": "Text size (px)",
"Automatique": "Automatic",
"Enregistrer (cette entreprise)": "Save (this company)",
"Enregistrer les modifications": "Save changes",
"Enregistrer le logo": "Save logo",
"Choisir le logo": "Choose logo",
"Enregistrer ma photo": "Save my photo",
"Prendre une photo": "Take a photo",
"Modèles": "Templates",
"Congés légaux": "Statutory leave",
"Ajouter / modifier": "Add / edit",
"Ajouter un document": "Add a document",
"Ajouter une ligne": "Add a row",
"Ajouter à la base": "Add to database",
"Donner l'accès": "Grant access",
"Interdire les imports": "Forbid imports",
"Interdire les suppressions": "Forbid deletions",
"Sauvegarde complète (JSON)": "Full backup (JSON)",
"Gestionnaire (peut modifier)": "Manager (can edit)",
"Cliquez sur un texte pour le modifier": "Click a text to edit it",
"Modifier ce texte": "Edit this text",
"Nouveau texte": "New text",
"Texte du dossier, tel qu'il sera imprimé.": "File text, as it will be printed.",
"Rétablir l'original": "Restore original",
"Mode « cliquer pour modifier »": "“Click to edit” mode",
"Menus visibles pour les non-propriétaires": "Menus visible to non-owners",
"Accès multi-sociétés (rôle par société)": "Multi-company access (role per company)",
"Que peut faire cette personne dans chaque module ?": "What can this person do in each module?",
"Voir comme (reproduire le problème d'un utilisateur)": "View as (reproduce a user's problem)",
"Retour à votre rôle": "Back to your role",
"Société non autorisée": "Company not authorised",
"Cette société n'est pas dans votre groupe": "This company is not in your group",
"Vous ne pouvez pas modifier vos propres accès": "You cannot change your own access",
"Import non autorisé pour votre compte": "Import not allowed for your account",
"Export désactivé pour votre compte": "Export disabled for your account",
"Suppression non autorisée pour votre compte": "Deletion not allowed for your account",
"Vos droits n'ont pas pu être lus. Réessayez dans un instant.": "Your permissions could not be read. Try again in a moment.",
"Réseau indisponible. Vérifiez votre connexion.": "Network unavailable. Check your connection.",
"État CNPS": "CNPS status",
"État virements": "Transfers status",
"État technique": "Technical status",
"Diagnostic des alertes": "Alerts diagnostic",
"Vue groupe détaillée": "Detailed group view",
"Saisie & états": "Entry & reports",
"Audit des données": "Data audit",
"Audit sécurité": "Security audit",
"Sécurité (contrôles réels)": "Security (real checks)",
"Activité récente (audit global)": "Recent activity (global audit)",
"Gérer ma 2FA": "Manage my 2FA",
"Vérification en deux étapes": "Two-step verification",
"Activée (application d'authentification).": "Enabled (authenticator app).",
"Envoyer un lien magique à": "Send a magic link to",
"DIPE depuis les bulletins": "DIPE from payslips",
"DIPE depuis des bulletins de paie": "DIPE from payslips",
"DIPE magnétique": "Magnetic DIPE",
"Lire les bulletins": "Read payslips",
"Exporter les manquants (Excel)": "Export missing (Excel)",
"Compléter depuis les fiches employés": "Complete from employee records",
"Supprimer les doublons vides": "Delete empty duplicates",
"Aucun doublon vide trouvé.": "No empty duplicates found.",
"Aucun doublon détecté": "No duplicates detected",
"Doublons détectés": "Duplicates detected",
"Générer pour les employés sans matricule": "Generate for employees without a number",
"Générer automatiquement pour les nouveaux employés": "Generate automatically for new employees",
"Tous les bulletins": "All payslips",
"Ancien modèle (.txt ou .xlsx)": "Old template (.txt or .xlsx)",
"Calculer avec les formules Sage": "Calculate with Sage formulas",
"Créer un classeur Excel (.xlsx)": "Create an Excel workbook (.xlsx)",
"Créer un document Word (.docx)": "Create a Word document (.docx)",
"Date": "Date",
"Date fin": "End date",
"Date expiration": "Expiry date",
"Date naissance": "Birth date",
"Date obtention": "Date obtained",
"Date paiement": "Payment date",
"Date publication": "Publication date",
"Date remise": "Handover date",
"Date restitution": "Return date",
"Date des faits": "Date of facts",
"Durée (heures)": "Duration (hours)",
"Emploi occupé": "Position held",
"Motif trop court (15 caractères minimum)": "Reason too short (minimum 15 characters)",
"Téléphone": "Phone",
"Modifié": "Modified",
"Ajouté": "Added",
"Toutes": "All",
"Aucune": "None",
"aucun": "none",
"aucune": "none",
"validé": "validated",
"à valider": "to validate",
"Édité le": "Issued on",
"Remplacé par": "Replaced by",
"Appliqué à": "Applied to",
"Envoyé à": "Sent to",
"Mi-année": "Mid-year",
"Non renseigné": "Not provided",
"non renseigné": "not provided",
"non renseignée": "not provided",
"non précisée": "not specified",
"Sexe non renseigné (M par défaut)": "Sex not provided (M by default)",
"Masculin, né le": "Male, born on",
"Féminin, née le": "Female, born on",
"Nous vous remercions pour votre collaboration.": "Thank you for your cooperation.",
"Comment puis-je vous aider ?": "How can I help you?",
"Voici mes priorités": "Here are my priorities",
"Je suis votre assistant RH chez": "I am your HR assistant at",
"Répondre à vos questions RH": "Answer your HR questions",
"Analyser les données": "Analyse the data",
"Rédiger une lettre ou un certificat": "Draft a letter or a certificate",
"Arrêter": "Stop",
"Réessayer": "Try again",
"Voix coupée": "Voice muted",
"Dictée terminée": "Dictation finished",
"Réponse copiée": "Reply copied",
"IA locale prête": "Local AI ready",
"IA locale désactivée": "Local AI disabled",
"Très léger": "Very light",
"Équilibré (conseillé)": "Balanced (recommended)",
"Téléphone ou PC modeste. Réponses simples.": "Phone or modest PC. Simple answers.",
"PC avec 8 Go de RAM ou plus.": "PC with 8 GB of RAM or more.",
"Chargement du modèle (2-5 min la 1ère fois)": "Loading model (2-5 min the first time)",
"Traduction anglaise complète (écrans, documents imprimés, voix, IA locale)": "Full English translation (screens, printed documents, voice, local AI)",
"Français (France)": "French (France)",
"Français (Canada)": "French (Canada)",
"Option avancée (administrateur)": "Advanced option (administrator)",
"Informations société": "Company information",
"Société configurée": "Company configured",
"Société cliente": "Client company",
"Aucune société mère définie": "No parent company defined",
"société unique": "single company",
"avec sous-organisations": "with sub-organisations",
"Sans aucune date de contrat": "No contract date",
"aucune date de contrat": "no contract date",
"— date, type, fichier, utilisateur et statut.": "— date, type, file, user and status.",
"lettre(s) de fin de contrat": "contract-end letter(s)",
"Compte rattaché": "Account linked",
"Accès enregistrés": "Access saved",
"Import accordé": "Import granted",
"Contrôles OK": "Checks OK",
"Création": "Creation"
});
try{if(window.TERH_I18N_add)window.TERH_I18N_add(window.TERH_I18N);}catch(e){}
